local dap = require('dap')
local fzf = require('fzf-lua')
vim.keymap.set('n', '<F5>', function() dap.continue() end, { desc = 'Continue (Debug)' })
vim.keymap.set('n', '<F10>', function() dap.step_over() end, { desc = 'Step over (Debug)' })
vim.keymap.set('n', '<F11>', function() dap.step_into() end, { desc = 'Step into (Debug)' })
vim.keymap.set('n', '<F12>', function() dap.step_out() end, { desc = 'Step out (Debug)' })
vim.keymap.set('n', '<leader>dd', fzf.dap_configurations, { desc = 'Run Configuration' })
vim.keymap.set('n', '<leader>dc', fzf.dap_commands, { desc = 'Commands' })
vim.keymap.set('n', '<leader>dv', fzf.dap_variables, { desc = 'Variables' })
vim.keymap.set('n', '<leader>df', fzf.dap_frames, { desc = 'Frames' })
vim.keymap.set('n', '<leader>db', function() dap.toggle_breakpoint() end, { desc = 'Toggle Breakpoint (Debug)' })
vim.keymap.set('n', '<leader>dB', function() dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, { desc = 'Breakpoint with message (Debug)' })
vim.keymap.set('n', '<leader>dl', function() dap.run_last() end, { desc = 'Run Last (Debug)' })
vim.keymap.set({'n', 'v'}, '<leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = 'Widgets (hover)' })
vim.keymap.set({'n', 'v'}, '<leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = 'Widgets (preview)' })

vim.fn.sign_define('DapBreakpoint',{ text ='🟥', texthl ='', linehl ='', numhl =''})
vim.fn.sign_define('DapStopped',{ text ='▶️', texthl ='', linehl ='', numhl =''})

local dapui = require('dapui')
dapui.setup() dap.listeners.after.event_initialized["dapui_config"]=function()
  dapui.open()
end
dap.listeners.before.event_terminated["dapui_config"]=function()
  dapui.close()
end
dap.listeners.before.event_exited["dapui_config"]=function()
  dapui.close()
end

require('dap-go').setup()
