# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-69941b1c-f90e-4adb-9391-9ebadffd11fb".device = "/dev/disk/by-uuid/69941b1c-f90e-4adb-9391-9ebadffd11fb";

  fileSystems."/boot/efi" = { 
    device = "/dev/disk/by-uuid/4315-D612";
    fsType = "vfat";
  };

  fileSystems."/nix" = { 
    device = "/dev/disk/by-uuid/395e6532-63cd-48f4-b556-7863e98197e2";
    fsType = "ext4";
    #fsType = "btrfs";
    #options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
